const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const cfg=window.VITX_CONFIG||{}; let supabase,demoMode=false,users=[],settings={system:{},activities:[],releases:[]},logs={usage:[],audit:[]},operations={dashboard:{},runtime_config:{},features:[],announcements:[],releases:[],errors:[],mfa_required:false},feedback=[],accessRequests=[],activeLog="usage",selectedUserId=null,demoDevices={},demoDeviceHistory={},pendingMfaSession=null;
const date=v=>v?new Intl.DateTimeFormat("th-TH",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
const localDate=v=>{const d=v?new Date(v):new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const toast=(m,bad=false)=>{const e=$("#toast");e.textContent=m;e.className="toast show"+(bad?" error":"");clearTimeout(toast.t);toast.t=setTimeout(()=>e.className="toast",3200)};
const setLoading=(on,message="กำลังโหลดข้อมูล…")=>{const e=$("#loadingOverlay");$("#loadingText").textContent=message;e.classList.toggle("hidden",!on)};
const buttonBusy=(button,on,label="กำลังดำเนินการ…")=>{if(!button)return;if(on){button.dataset.originalHtml=button.innerHTML;button.disabled=true;button.classList.add("is-loading");button.innerHTML='<span class="spinner"></span><span>'+esc(label)+"</span>"}else{button.disabled=false;button.classList.remove("is-loading");if(button.dataset.originalHtml)button.innerHTML=button.dataset.originalHtml}};
const rpc=async(n,p={})=>{if(demoMode){if(n==="admin_get_user_activities")return settings.activities.map(a=>({...a,global_enabled:a.enabled,enabled:false}));if(n==="admin_list_user_devices")return demoDevices[p.p_user_id]||[];if(n==="admin_list_user_device_history")return demoDeviceHistory[p.p_user_id]||{summary:{},events:[]};if(n==="admin_list_feedback")return feedback;if(n==="admin_list_access_requests")return accessRequests;if(n==="admin_review_access_request"){const item=accessRequests.find(x=>x.id===p.p_id);if(item)item.status=p.p_status;return {ok:true}}if(n==="admin_update_feedback"){const item=feedback.find(x=>x.id===p.p_id);if(item){item.status=p.p_status;item.admin_note=p.p_admin_note||""}return {ok:true}}if(n==="admin_force_logout")return {ok:true,revoked_sessions:1};if(n==="admin_reset_device"){demoDevices[p.p_user_id]=(demoDevices[p.p_user_id]||[]).filter(d=>d.device_id!==p.p_device_id);return {ok:true}}}const {data,error}=await supabase.rpc(n,p);if(error)throw error;return data};

async function boot(){
 if(location.hostname==="127.0.0.1"&&new URLSearchParams(location.search).has("demo")){loadDemo();setLoading(false);return}
 if(!cfg.supabaseUrl||!cfg.supabasePublishableKey){$("#setupView").classList.remove("hidden");setLoading(false);return}
 const {createClient}=await import("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm");
 supabase=createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true}});
 const {data}=await supabase.auth.getSession();if(data.session)await completeAdminSignIn(data.session);else $("#loginView").classList.remove("hidden");setLoading(false)
}
function loadDemo(){
 demoMode=true;
 $("#appView").classList.remove("hidden");$("#adminName").textContent="Owner";
 users=[
  {id:"1",username:"mint",display_name:"Mint S.",enabled:true,online:true,current_device_name:"MINT-PC",current_device_type:"Windows PC",current_app_version:"1.0.0",current_ip:"203.0.113.24",device_count:2,starts_at:new Date(Date.now()-10*86400000),expires_at:new Date(Date.now()+20*86400000),last_login_at:new Date()},
  {id:"2",username:"beam",display_name:"Beam",enabled:true,online:false,starts_at:new Date(Date.now()-25*86400000),expires_at:new Date(Date.now()+5*86400000),last_login_at:new Date(Date.now()-2*3600000)},
  {id:"3",username:"night",display_name:"Night",enabled:false,approval_status:"pending",online:false,starts_at:new Date(),expires_at:new Date(Date.now()+30*86400000),last_login_at:null}
 ];
 demoDevices={"1":[{device_id:"demo-device-a1b2c3d4",device_name:"MINT-PC",device_type:"Windows PC",os_name:"Windows",os_version:"11 (10.0.26100)",architecture:"AMD64",app_version:"1.0.0",last_login_at:new Date(),last_seen_at:new Date(),last_ip:"203.0.113.24",login_count:8,online:true},{device_id:"demo-device-old12345",device_name:"MINT-NOTEBOOK",device_type:"Windows PC",os_name:"Windows",os_version:"10",architecture:"AMD64",app_version:"1.0.0",last_login_at:new Date(Date.now()-15*86400000),last_seen_at:new Date(Date.now()-15*86400000),last_ip:"198.51.100.18",login_count:3,online:false}]};
 demoDeviceHistory={"1":{summary:{total_logins:11,unique_devices:2,logins_30d:6,devices_30d:2},events:[{device_id:"demo-device-a1b2c3d4",device_name:"MINT-PC",device_type:"Windows PC",os_name:"Windows",os_version:"11 (10.0.26100)",architecture:"AMD64",app_version:"1.0.0",client_ip:"203.0.113.24",logged_in_at:new Date()},{device_id:"demo-device-old12345",device_name:"MINT-NOTEBOOK",device_type:"Windows PC",os_name:"Windows",os_version:"10",architecture:"AMD64",app_version:"1.0.0",client_ip:"198.51.100.18",logged_in_at:new Date(Date.now()-15*86400000)},{device_id:"demo-device-a1b2c3d4",device_name:"MINT-PC",device_type:"Windows PC",os_name:"Windows",os_version:"11 (10.0.26100)",architecture:"AMD64",app_version:"1.0.0",client_ip:"203.0.113.44",logged_in_at:new Date(Date.now()-22*86400000)}]}};
 settings={system:{system_enabled:true,maintenance_mode:false,maintenance_message:"",session_lease_seconds:300,minimum_version:"1.0.0",latest_version:"1.0.0",update_available:false,update_required:false,update_message:""},
  activities:[{activity_key:"daily_login",name:"Daily Login",description:"รับรางวัลรายวัน เก็บโค้ด และใช้โค้ดอัตโนมัติ",enabled:true,visible:true,sort_order:10},{activity_key:"special_event",name:"กิจกรรมพิเศษ",description:"เตรียมเปิดใช้งานในอนาคต",enabled:false,visible:true,sort_order:20},{activity_key:"seasonal_event",name:"กิจกรรมตามเทศกาล",description:"กำหนดจากหน้า Admin",enabled:false,visible:false,sort_order:30}],
  releases:[{version:"1.0.0",title:"VITX Launcher",release_notes:"รุ่นเริ่มต้นสำหรับผู้ใช้ใหม่",enabled:true,required:false,published_at:new Date()}]};
 logs={usage:[{created_at:new Date(),display_name:"Mint S.",event_type:"login",activity_key:null,success:true}],audit:[]};
 operations={dashboard:{database_online:true,active_sessions:1,daily_active_users:2,activity_runs_7d:18,success_7d:16,failed_7d:2,open_errors:1,errors_24h:1,latest_launcher:"1.0.1",checked_at:new Date()},runtime_config:{browser_timeout_ms:25000,request_timeout_ms:25000,delay_min_seconds:1,delay_max_seconds:3,max_retry:2,error_reporting_enabled:true},retention_days:90,mfa_required:false,features:[{activity_key:"daily_login",feature_key:"claim",name:"รับรางวัลรายวัน",enabled:true},{activity_key:"daily_login",feature_key:"export",name:"ส่งออกโค้ด",enabled:true},{activity_key:"daily_login",feature_key:"redeem",name:"ใช้โค้ด",enabled:true}],announcements:[{id:"demo",title:"แจ้งปรับปรุง",message:"ระบบพร้อมใช้งานตามปกติ",severity:"info",enabled:true,starts_at:new Date()}],errors:[{id:1,error_code:"VITX-E1024ABCD",username:"mint",activity_key:"daily_login",error_type:"TimeoutError",app_version:"1.0.1",occurred_at:new Date()}]};
 feedback=[{id:"feedback-demo",category:"suggestion",title:"อยากให้เพิ่มตัวกรองบัญชี",message:"ถ้ามีช่องค้นหาบัญชีในหน้ากิจกรรมจะใช้งานสะดวกขึ้นครับ",activity_key:"daily_login",app_version:"1.0.1",device_id:"demo-device-a1b2c3d4",status:"new",admin_note:"",created_at:new Date(),username:"mint",display_name:"Mint S."}];
 accessRequests=[{id:"request-demo",activity_key:"special_event",activity_name:"กิจกรรมพิเศษ",message:"อยากทดลองกิจกรรมนี้",status:"pending",created_at:new Date(),user_id:"2",username:"beam",display_name:"Beam"}];
 renderStats({total_users:3,pending_users:1,online_users:1,expiring_7_days:1,expired_users:0});renderUsers();renderActivities();renderSystem();renderReleases();renderLogs();renderOperations();renderFeedback();renderAccessRequests()
}
$("#loginForm").addEventListener("submit",async e=>{
 e.preventDefault();const button=e.submitter;buttonBusy(button,true,"กำลังเข้าสู่ระบบ…");setLoading(true,"กำลังตรวจสอบสิทธิ์ผู้ดูแล…");$("#loginError").textContent="";
 try{const {data,error}=await supabase.auth.signInWithPassword({email:$("#email").value.trim(),password:$("#password").value});if(error)throw Error("INVALID_LOGIN");await completeAdminSignIn(data.session)}catch(x){if(x.message!=="INVALID_LOGIN")await supabase.auth.signOut();$("#loginError").textContent=x.message==="INVALID_LOGIN"?"อีเมลหรือรหัสผ่านไม่ถูกต้อง":(x.message.includes("ADMIN_REQUIRED")?"บัญชีนี้ไม่ได้รับสิทธิ์ผู้ดูแล":x.message)}finally{setLoading(false);buttonBusy(button,false)}
});
async function completeAdminSignIn(session){
 if(demoMode)return enter(session);
 const [{data:factors},{data:aal}]=await Promise.all([supabase.auth.mfa.listFactors(),supabase.auth.mfa.getAuthenticatorAssuranceLevel()]);
 const factor=(factors?.totp||[]).find(x=>x.status==="verified");
 if(factor&&aal?.currentLevel!=="aal2"){pendingMfaSession=session;$("#mfaChallengeForm").elements.factor_id.value=factor.id;$("#mfaChallengeForm").reset();$("#mfaChallengeForm").elements.factor_id.value=factor.id;$("#mfaChallengeDialog").showModal();setLoading(false);return}
 await enter(session)
}
async function enter(s){if(!await rpc("is_admin"))throw Error("ADMIN_REQUIRED");$("#adminName").textContent=s.user.email?.split("@")[0]||"Administrator";$("#loginView").classList.add("hidden");$("#appView").classList.remove("hidden");await loadAll()}
async function loadAll(){
 try{const r=await Promise.all([rpc("admin_dashboard"),rpc("admin_list_users",{p_search:""}),rpc("admin_get_settings"),rpc("admin_list_logs",{p_limit:100}),rpc("admin_operational_dashboard"),rpc("admin_get_operational_settings"),rpc("admin_list_error_reports",{p_limit:100}),rpc("admin_list_feedback",{p_status:null,p_limit:200}),rpc("admin_list_access_requests",{p_status:null,p_limit:200})]);
 users=r[1]||[];settings=r[2]||settings;logs=r[3]||logs;operations={...(r[5]||{}),dashboard:r[4]||{},errors:r[6]||[]};feedback=r[7]||[];accessRequests=r[8]||[];if(operations.releases)settings.releases=operations.releases;renderStats(r[0]);renderUsers();renderActivities();renderSystem();renderReleases();renderLogs();renderFeedback();renderAccessRequests();await renderOperations()}
 catch(x){toast(x.message||"โหลดข้อมูลไม่สำเร็จ",true)}
}
function renderStats(s={}){
 const cards=[["ผู้ใช้ทั้งหมด",s.total_users||0,""],["รออนุมัติ",s.pending_users||0,"warn"],["กำลังออนไลน์",s.online_users||0,"good"],["ใกล้หมดอายุ 7 วัน",s.expiring_7_days||0,"warn"],["หมดอายุแล้ว",s.expired_users||0,"bad"]];
 $("#stats").innerHTML=cards.map(x=>'<article class="stat-card '+x[2]+'"><div class="value">'+x[1]+'<i></i></div><small>'+x[0]+"</small></article>").join("");
 $("#recentUsers").className="compact-list";$("#recentUsers").innerHTML=users.slice(0,6).map(u=>'<div class="compact-item"><span class="status-dot '+(u.online?"on":"")+'"></span><div class="meta"><b>'+esc(u.display_name)+"</b><small>@"+esc(u.username)+"</small></div><small>"+(u.online?"ออนไลน์":date(u.last_login_at))+"</small></div>").join("")||'<div class="empty">ยังไม่มีผู้ใช้</div>';
 const s1=settings.system||{},badge=$("#systemBadge");badge.className="badge "+(!s1.system_enabled||s1.maintenance_mode?"warn":"success");badge.textContent=s1.maintenance_mode?"● ปิดปรับปรุง":(!s1.system_enabled?"● ปิดระบบ":"● ระบบพร้อมใช้งาน");
 $("#activitySummary").className="compact-list";$("#activitySummary").innerHTML=(settings.activities||[]).map(a=>'<div class="compact-item"><span class="activity-icon">◇</span><div class="meta"><b>'+esc(a.name)+"</b><small>"+(a.visible?"แสดงในแอพ":"ซ่อนจากแอพ")+'</small></div><span class="badge '+(a.enabled?"success":"warn")+'">'+(a.enabled?"เปิด":"ปิด")+"</span></div>").join("")||'<div class="empty">ยังไม่มีกิจกรรม</div>'
}
const userStatus=u=>u.approval_status==="pending"?["รออนุมัติ","pending"]:(!u.enabled?["ปิดใช้งาน","danger"]:(new Date(u.expires_at)<=new Date()?["หมดอายุ","danger"]:(u.online?["ออนไลน์","success"]:["พร้อมใช้","warn"])));
function renderUsers(){
 const q=$("#userSearch").value.trim().toLowerCase(),rows=users.filter(u=>!q||u.username.toLowerCase().includes(q)||u.display_name.toLowerCase().includes(q));
 $("#usersTable").innerHTML=rows.map(u=>{const st=userStatus(u),device=u.current_device_name||u.current_device_type||((u.device_count||0)+" เครื่อง");return '<tr><td><div class="user-cell"><b>'+esc(u.display_name)+"</b><small>@"+esc(u.username)+'</small></div></td><td><span class="badge '+st[1]+'">'+st[0]+'</span></td><td><div class="user-cell"><b>'+esc(device||"ยังไม่มีข้อมูล")+'</b><small>'+(u.online?"กำลังใช้งาน":"ประวัติ "+(u.device_count||0)+" เครื่อง")+'</small></div></td><td>'+esc(u.current_app_version||"—")+'</td><td>'+date(u.expires_at)+"</td><td>"+date(u.last_login_at)+'</td><td><div class="row-actions"><button class="action-btn" data-edit-user="'+u.id+'">จัดการ</button></div></td></tr>'}).join("")||'<tr><td colspan="7" class="empty">ไม่พบผู้ใช้</td></tr>'
}

const approximateIp=value=>{const ip=String(value||"");if(!ip)return "—";if(ip.includes(".")){const p=ip.split(".");if(p.length===4)p[3]="xxx";return p.join(".")}if(ip.includes(":"))return ip.split(":").slice(0,4).join(":")+"::";return ip};
function renderDevices(rows=[]){
 $("#userDeviceList").innerHTML=rows.map(d=>'<article class="device-item"><div class="device-main"><b>'+(d.online?'<span class="online-dot">●</span> ':'')+esc(d.device_name||d.device_type||"Windows PC")+'</b><small>'+esc([d.os_name,d.os_version,d.architecture].filter(Boolean).join(" · ")||"ไม่ทราบรุ่นระบบ")+'</small><span class="device-id">'+esc(d.device_id)+'</span></div><div class="device-meta"><small>เข้าใช้ล่าสุด: '+date(d.last_login_at)+'</small><small>พบล่าสุด: '+date(d.last_seen_at)+'</small><small>IP โดยประมาณ: '+esc(approximateIp(d.last_ip))+'</small><small>VITX '+esc(d.app_version||"—")+' · '+Number(d.login_count||0)+' ครั้ง</small></div><div class="device-actions"><button type="button" class="action-btn" data-device-logout="'+esc(d.device_id)+'">Force Logout</button><button type="button" class="action-btn danger" data-device-reset="'+esc(d.device_id)+'">Reset Device</button></div></article>').join("")||'<div class="empty">ยังไม่มีข้อมูลอุปกรณ์ ผู้ใช้ต้องเข้า Launcher รุ่นที่รองรับอย่างน้อยหนึ่งครั้ง</div>'
}
function renderDeviceHistory(data={}){
 const s=data.summary||{},events=data.events||[];
 $("#deviceHistorySummary").innerHTML=[["Login ทั้งหมด",s.total_logins||0],["เครื่องทั้งหมด",s.unique_devices||0],["Login 30 วัน",s.logins_30d||0],["เครื่องใน 30 วัน",s.devices_30d||0]].map(x=>'<div><b>'+Number(x[1])+'</b><small>'+x[0]+'</small></div>').join("");
 $("#userDeviceHistory").innerHTML=events.map(e=>'<article class="history-item"><div class="history-time"><b>'+date(e.logged_in_at)+'</b><small>IP '+esc(approximateIp(e.client_ip))+'</small></div><div class="history-device"><b>'+esc(e.device_name||e.device_type||"Windows PC")+'</b><small>'+esc([e.os_name,e.os_version,e.architecture].filter(Boolean).join(" · ")||"ไม่ทราบรุ่นระบบ")+'</small><span class="device-id">'+esc(e.device_id)+'</span></div><div class="history-version">VITX '+esc(e.app_version||"—")+'</div></article>').join("")||'<div class="empty">ยังไม่มีประวัติการเข้าใช้</div>';
}
function renderActivities(){
 $("#activitiesGrid").innerHTML=(settings.activities||[]).map((a,index)=>'<article class="card activity-card"><div class="title-row"><span class="activity-icon">'+(index+1)+'</span><div><h3>'+esc(a.name)+"</h3><p>"+esc(a.activity_key)+" · ลำดับที่ "+(index+1)+"</p></div></div><p>"+esc(a.description||"ยังไม่มีคำอธิบาย")+'</p><div class="activity-footer"><div><span class="badge '+(a.enabled?"success":"warn")+'">'+(a.enabled?"เปิดใช้งาน":"ปิดใช้งาน")+"</span>"+(a.visible?"":'<span class="badge warn">ซ่อน</span>')+'</div><button class="action-btn" data-edit-activity="'+esc(a.activity_key)+'">แก้ไข</button></div></article>').join("")||'<div class="empty">ยังไม่มีกิจกรรม</div>'
}
function renderSystem(){const f=$("#systemForm"),s=settings.system||{};["system_enabled","maintenance_mode","update_available","update_required"].forEach(k=>f.elements[k].checked=!!s[k]);["maintenance_message","session_lease_seconds","minimum_version","latest_version","update_message"].forEach(k=>f.elements[k].value=s[k]??"")}
function renderReleases(){
 $("#releasesList").innerHTML=(settings.releases||[]).map(r=>'<article class="card release-card"><div class="version">v'+esc(r.version)+"</div><div><b>"+esc(r.title)+"</b><p>"+esc((r.channel||"stable").toUpperCase())+" · เผยแพร่ "+date(r.published_at)+'</p></div><div><span class="badge '+((r.status||"active")==="blocked"?"danger":(r.enabled?"success":"warn"))+'">'+esc(r.status||(r.enabled?"active":"disabled"))+"</span>"+(r.required?'<span class="badge danger">บังคับ</span>':"")+"</div></article>").join("")||'<article class="card empty">ยังไม่มี Release</article>'
}
async function renderOperations(){
 const d=operations.dashboard||{};let updateOnline=false;
 if(!demoMode){try{const response=await fetch("https://api.github.com/repos/vitawatvim/VITXUpdates/releases/latest",{headers:{Accept:"application/vnd.github+json"}});updateOnline=response.ok}catch{updateOnline=false}}else updateOnline=true;
 const health=[["API","Online",false],["Database",d.database_online?"Online":"Offline",!d.database_online],["Update Server",updateOnline?"Online":"Offline",!updateOnline],["Latest Launcher",d.latest_launcher||"—",!d.latest_launcher],["Active Sessions",Number(d.active_sessions||0),false],["Daily Active Users",Number(d.daily_active_users||0),false],["Runs 7 days",Number(d.runs_7_days||0),false],["Success 7 days",Number(d.success_7_days||0),false],["Failed 7 days",Number(d.failed_7_days||0),Number(d.failed_7_days||0)>0],["Errors 24h",Number(d.errors_24_hours||0),Number(d.errors_24_hours||0)>0]];
 $("#healthGrid").innerHTML=health.map(x=>'<article class="health-card '+(x[2]?"bad":"")+'"><small>'+x[0]+'</small><span class="health-value">'+esc(x[1])+'</span><small>ตรวจล่าสุด '+date(d.checked_at||new Date())+'</small></article>').join("");
 const f=$("#runtimeForm"),c=operations.runtime_config||{};["browser_timeout_ms","request_timeout_ms","delay_min_seconds","delay_max_seconds","max_retry"].forEach(k=>f.elements[k].value=c[k]??"");f.elements.retention_days.value=operations.retention_days||90;f.elements.error_reporting_enabled.checked=c.error_reporting_enabled!==false;
 $("#mfaStatus").innerHTML='<b>'+(operations.mfa_required?"บังคับ MFA แล้ว":"ยังไม่บังคับ MFA")+'</b><br><small>'+(operations.mfa_required?"RPC สำหรับผู้ดูแลต้องยืนยันระดับ AAL2":"ตั้งค่า Authenticator ให้เสร็จก่อนเปิดสวิตช์")+'</small>';$("#toggleMfaBtn").textContent=operations.mfa_required?"ปิดการบังคับ MFA":"เปิดบังคับ MFA";
 const grouped={};(operations.features||[]).forEach(x=>(grouped[x.activity_key]??=[]).push(x));$("#featureFlagsList").innerHTML=Object.entries(grouped).map(([key,items])=>'<div class="feature-group"><strong>'+esc((settings.activities||[]).find(a=>a.activity_key===key)?.name||key)+'</strong>'+items.map(x=>'<label class="switch-row"><div><b>'+esc(x.name)+'</b><small>'+esc(x.feature_key)+'</small></div><input type="checkbox" data-feature-activity="'+esc(key)+'" data-feature-key="'+esc(x.feature_key)+'" data-feature-name="'+esc(x.name)+'" '+(x.enabled?"checked":"")+'><span class="switch"></span></label>').join("")+'</div>').join("")||'<div class="empty">ยังไม่มี Feature Flag</div>';
 $("#announcementsList").innerHTML=(operations.announcements||[]).map(a=>'<article class="announcement-item"><div class="meta"><b>'+esc(a.title)+' <span class="badge '+(a.severity==="critical"?"danger":a.severity==="warning"?"warn":"success")+'">'+esc(a.severity)+'</span></b><small>'+esc(a.message)+'</small><small>'+date(a.starts_at)+(a.ends_at?" – "+date(a.ends_at):"")+'</small></div><div class="announcement-actions"><button class="action-btn" data-edit-announcement="'+a.id+'">แก้ไข</button><button class="action-btn danger" data-delete-announcement="'+a.id+'">ลบ</button></div></article>').join("")||'<div class="empty">ยังไม่มีประกาศ</div>';
 $("#errorCount").textContent=Number(d.open_errors||0)+" รายการที่ยังไม่ปิด";$("#errorsTable").innerHTML=(operations.errors||[]).map(e=>'<tr><td>'+date(e.occurred_at)+'</td><td class="error-code">'+esc(e.error_code)+'</td><td>'+esc(e.username||"—")+'</td><td>'+esc(e.activity_key||"—")+'</td><td>'+esc(e.error_type)+'</td><td>'+esc(e.app_version||"—")+'</td><td>'+(e.resolved_at?'<span class="badge success">แก้แล้ว</span>':'<button class="action-btn" data-resolve-error="'+e.id+'">ปิดเคส</button>')+'</td></tr>').join("")||'<tr><td colspan="7" class="empty">ยังไม่มี Error Report</td></tr>';
}
function renderLogs(){
 $$(".tab").forEach(t=>t.classList.toggle("active",t.dataset.log===activeLog));
 if(activeLog==="usage"){ $("#logsHead").innerHTML="<tr><th>เวลา</th><th>ผู้ใช้</th><th>เหตุการณ์</th><th>กิจกรรม</th><th>ผลลัพธ์</th></tr>";$("#logsTable").innerHTML=(logs.usage||[]).map(x=>"<tr><td>"+date(x.created_at)+"</td><td>"+esc(x.display_name||x.username||"—")+"</td><td>"+esc(x.event_type)+"</td><td>"+esc(x.activity_key||"—")+'</td><td><span class="badge '+(x.success?"success":"danger")+'">'+(x.success?"สำเร็จ":"ผิดพลาด")+"</span></td></tr>").join("")||'<tr><td colspan="5" class="empty">ยังไม่มีประวัติ</td></tr>'}
 else{$("#logsHead").innerHTML="<tr><th>เวลา</th><th>ผู้ดูแล</th><th>การทำงาน</th><th>เป้าหมาย</th></tr>";$("#logsTable").innerHTML=(logs.audit||[]).map(x=>"<tr><td>"+date(x.created_at)+"</td><td>"+esc(x.admin_name)+"</td><td>"+esc(x.action)+"</td><td>"+esc(x.target_type)+" · "+esc(x.target_id||"—")+"</td></tr>").join("")||'<tr><td colspan="4" class="empty">ยังไม่มีประวัติ</td></tr>'}
}
function renderFeedback(){
 const filter=$("#feedbackStatusFilter")?.value||"",category={suggestion:"ข้อเสนอแนะ",problem:"แจ้งปัญหา",activity:"กิจกรรม",other:"อื่น ๆ"},status={new:["ใหม่","warn"],reviewing:["กำลังตรวจ","pending"],resolved:["ปิดแล้ว","success"],archived:["เก็บถาวร",""]},rows=feedback.filter(x=>!filter||x.status===filter);
 $("#feedbackList").innerHTML=rows.map(x=>{const st=status[x.status]||status.new;return '<article class="card feedback-card" data-feedback-card="'+x.id+'"><div class="feedback-head"><div class="feedback-user"><b>'+esc(x.title)+'</b><small>'+esc(x.display_name||x.username||"—")+' · @'+esc(x.username||"—")+'</small><div class="feedback-meta"><span>'+date(x.created_at)+'</span><span>'+esc(category[x.category]||x.category)+'</span><span>Activity: '+esc(x.activity_key||"—")+'</span><span>VITX '+esc(x.app_version||"—")+'</span><span>Device: '+esc(x.device_id||"—")+'</span></div></div><span class="badge '+st[1]+'">'+st[0]+'</span></div><div class="feedback-message">'+esc(x.message)+'</div><div class="feedback-controls"><label>สถานะ<select data-feedback-status><option value="new">ใหม่</option><option value="reviewing">กำลังตรวจ</option><option value="resolved">ปิดแล้ว</option><option value="archived">เก็บถาวร</option></select></label><label>บันทึกของผู้ดูแล<textarea data-feedback-note maxlength="2000" placeholder="บันทึกภายในสำหรับติดตามเรื่องนี้">'+esc(x.admin_note||"")+'</textarea></label><button class="btn primary" data-save-feedback="'+x.id+'">บันทึก</button></div></article>'}).join("")||'<div class="card empty">ยังไม่มีข้อเสนอแนะในสถานะนี้</div>';
 rows.forEach(x=>{const card=$("[data-feedback-card='"+x.id+"']");if(card)$("[data-feedback-status]",card).value=x.status});
}
function renderAccessRequests(){
 const rows=accessRequests||[];
 $("#accessRequestsList").innerHTML=rows.map(x=>'<article class="card feedback-card"><div class="feedback-head"><div class="feedback-user"><b>'+esc(x.activity_name||x.activity_key)+'</b><small>'+esc(x.display_name||x.username)+' · @'+esc(x.username)+'</small><div class="feedback-meta"><span>'+date(x.created_at)+'</span><span>'+esc(x.activity_key)+'</span></div></div><span class="badge '+(x.status==="pending"?"warn":x.status==="approved"?"success":"danger")+'">'+esc(x.status)+'</span></div><div class="feedback-message">'+esc(x.message||"ไม่ได้ระบุข้อความ")+'</div>'+(x.status==="pending"?'<div class="feedback-controls"><label>บันทึกผู้ดูแล<textarea data-request-note maxlength="1000"></textarea></label><div class="dialog-actions"><button class="btn danger" data-review-request="'+x.id+'" data-status="rejected">ปฏิเสธ</button><button class="btn primary" data-review-request="'+x.id+'" data-status="approved">อนุมัติสิทธิ์</button></div></div>':"")+'</article>').join("")||'<div class="card empty">ยังไม่มีคำขอสิทธิ์</div>';
}
function showPage(n){$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.page===n));$$(".page").forEach(x=>x.classList.toggle("active",x.id==="page-"+n));$("#pageTitle").textContent=({dashboard:"ภาพรวมระบบ",users:"ผู้ใช้งาน",activities:"กิจกรรม",system:"ตั้งค่าระบบ",updates:"อัปเดต",operations:"Operations Center",feedback:"ข้อเสนอแนะจากผู้ใช้",requests:"คำขอเปิดสิทธิ์",logs:"ประวัติการใช้งาน"})[n]}
$("#nav").addEventListener("click",e=>{const b=e.target.closest("[data-page]");if(b)showPage(b.dataset.page)});document.addEventListener("click",e=>{const b=e.target.closest("[data-goto]");if(b)showPage(b.dataset.goto)});
$("#userSearch").addEventListener("input",renderUsers);$("#refreshBtn").addEventListener("click",async()=>{setLoading(true,"กำลังรีเฟรชข้อมูล…");try{await loadAll()}finally{setLoading(false)}});$("#logoutBtn").addEventListener("click",async()=>{await supabase.auth.signOut();location.reload()});
$$("[data-close]").forEach(b=>b.addEventListener("click",()=>b.closest("dialog").close()));$$(".tab").forEach(b=>b.addEventListener("click",()=>{activeLog=b.dataset.log;renderLogs()}));
$("#addUserBtn").addEventListener("click",()=>{selectedUserId=null;const f=$("#userForm");f.reset();f.elements.id.value="";f.elements.enabled.checked=true;f.elements.update_channel.value="stable";f.elements.starts_at.value=localDate();f.elements.expires_at.value=localDate(Date.now()+30*86400000);$("#userDialogTitle").textContent="สร้างผู้ใช้";$("#passwordField").classList.remove("hidden");$("#userActivities").classList.add("hidden");$("#userApprovalNote").classList.add("hidden");$("#userEnabledTitle").textContent="เปิดใช้งานบัญชี";$("#userEnabledHelp").textContent="";f.elements.password.required=true;$$(".edit-only",f).forEach(x=>x.classList.add("hidden"));f.elements.username.disabled=false;$("#userDialog").showModal()});
$("#usersTable").addEventListener("click",async e=>{const b=e.target.closest("[data-edit-user]");if(!b)return;const u=users.find(x=>x.id===b.dataset.editUser),f=$("#userForm"),pending=u.approval_status==="pending";selectedUserId=u.id;f.reset();["id","username","display_name","notes"].forEach(k=>f.elements[k].value=u[k]||"");f.elements.starts_at.value=localDate(u.starts_at);f.elements.expires_at.value=localDate(u.expires_at);f.elements.enabled.checked=u.enabled;f.elements.update_channel.value=u.update_channel||"stable";f.elements.username.disabled=true;f.elements.password.required=false;$("#passwordField").classList.add("hidden");$$(".edit-only",f).forEach(x=>x.classList.remove("hidden"));$("#userDialogTitle").textContent=pending?"อนุมัติผู้สมัคร":"จัดการผู้ใช้";$("#userApprovalNote").classList.toggle("hidden",!pending);$("#userEnabledTitle").textContent=pending?"อนุมัติให้เข้าใช้งาน":"เปิดใช้งานบัญชี";$("#userEnabledHelp").textContent=pending?"เปิดสวิตช์นี้และเลือกกิจกรรมด้านล่าง":"";$("#userActivities").classList.remove("hidden");$("#userActivityList").innerHTML='<div class="empty">กำลังโหลด…</div>';$("#userDeviceList").innerHTML='<div class="empty">กำลังโหลด…</div>';$("#deviceHistorySummary").innerHTML="";$("#userDeviceHistory").innerHTML='<div class="empty">กำลังโหลด…</div>';$("#userDialog").showModal();try{const [activities,devices,history]=await Promise.all([rpc("admin_get_user_activities",{p_user_id:u.id}),rpc("admin_list_user_devices",{p_user_id:u.id}),rpc("admin_list_user_device_history",{p_user_id:u.id,p_limit:100})]);$("#userActivityList").innerHTML=(activities||[]).map(a=>'<label class="switch-row"><div><b>'+esc(a.name)+'</b><small>สิทธิ์ของผู้ใช้นี้ · ค่าเริ่มต้นระบบ: '+(a.global_enabled?"เปิด":"ปิด")+'</small></div><input type="checkbox" data-user-activity="'+esc(a.activity_key)+'" '+(a.enabled?"checked":"")+'><span class="switch"></span></label>').join("")||'<div class="empty">ไม่มีกิจกรรม</div>';renderDevices(devices||[]);renderDeviceHistory(history||{})}catch(x){toast(x.message,true);renderDevices([]);renderDeviceHistory({})}});
$("#userForm").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,id=f.elements.id.value,button=e.submitter;buttonBusy(button,true,"กำลังบันทึก…");try{if(id){await rpc("admin_update_user",{p_user_id:id,p_display_name:f.elements.display_name.value,p_enabled:f.elements.enabled.checked,p_starts_at:new Date(f.elements.starts_at.value).toISOString(),p_expires_at:new Date(f.elements.expires_at.value).toISOString(),p_notes:f.elements.notes.value});await Promise.all([...$$("[data-user-activity]",f).map(input=>rpc("admin_set_user_activity",{p_user_id:id,p_activity_key:input.dataset.userActivity,p_enabled:input.checked})),rpc("admin_set_user_update_channel",{p_user_id:id,p_channel:f.elements.update_channel.value})])}else await rpc("admin_create_user",{p_username:f.elements.username.value,p_password:f.elements.password.value,p_display_name:f.elements.display_name.value,p_starts_at:new Date(f.elements.starts_at.value).toISOString(),p_expires_at:new Date(f.elements.expires_at.value).toISOString(),p_notes:f.elements.notes.value});$("#userDialog").close();toast("บันทึกผู้ใช้แล้ว");await loadAll()}catch(x){toast(x.message,true)}finally{buttonBusy(button,false)}});
$("#resetPasswordBtn").addEventListener("click",async()=>{const p=prompt("รหัสผ่านใหม่ (อย่างน้อย 10 ตัวอักษร)");if(!p)return;try{await rpc("admin_reset_password",{p_user_id:$("#userForm").elements.id.value,p_new_password:p});toast("รีเซ็ตรหัสผ่านและตัด session แล้ว")}catch(x){toast(x.message,true)}});
$("#rotateRecoveryBtn").addEventListener("click",async e=>{const button=e.currentTarget;buttonBusy(button,true,"กำลังสร้าง…");try{const result=await rpc("admin_rotate_recovery_code",{p_user_id:$("#userForm").elements.id.value});$("#recoveryCodeValue").value=result.recovery_code;$("#recoveryCodeDialog").showModal()}catch(x){toast(x.message,true)}finally{buttonBusy(button,false)}});
$("#copyRecoveryBtn").addEventListener("click",async()=>{try{await navigator.clipboard.writeText($("#recoveryCodeValue").value);toast("คัดลอก Recovery Code แล้ว")}catch{$("#recoveryCodeValue").select();document.execCommand("copy");toast("คัดลอก Recovery Code แล้ว")}});
$("#revokeBtn").addEventListener("click",async()=>{try{await rpc("admin_revoke_session",{p_user_id:$("#userForm").elements.id.value});$("#userDialog").close();toast("ตัด session แล้ว");await loadAll()}catch(x){toast(x.message,true)}});
async function reloadSelectedDevices(){if(!selectedUserId)return;renderDevices(await rpc("admin_list_user_devices",{p_user_id:selectedUserId})||[])}
$("#forceLogoutAllBtn").addEventListener("click",async e=>{if(!selectedUserId||!confirm("Force Logout ผู้ใช้นี้จากทุกเครื่องตอนนี้หรือไม่?"))return;const button=e.currentTarget;buttonBusy(button,true,"กำลังตัด Session…");try{const result=await rpc("admin_force_logout",{p_user_id:selectedUserId,p_device_id:null});toast("ตัด Session แล้ว "+Number(result.revoked_sessions||0)+" รายการ");await reloadSelectedDevices();if(!demoMode)await loadAll()}catch(x){toast(x.message,true)}finally{buttonBusy(button,false)}});
$("#userDeviceList").addEventListener("click",async e=>{const logout=e.target.closest("[data-device-logout]"),reset=e.target.closest("[data-device-reset]");if(!logout&&!reset||!selectedUserId)return;const deviceId=(logout||reset).dataset[logout?"deviceLogout":"deviceReset"],button=logout||reset;if(reset&&!confirm("Reset Device นี้หรือไม่? ระบบจะตัด Session ปัจจุบันและซ่อนประวัติรายการนี้ แต่ผู้ใช้ยังล็อกอินจากเครื่องเดิมหรือเครื่องใหม่ได้ตามปกติ"))return;if(logout&&!confirm("Force Logout อุปกรณ์นี้ตอนนี้หรือไม่?"))return;buttonBusy(button,true,reset?"กำลัง Reset…":"กำลัง Logout…");try{if(reset)await rpc("admin_reset_device",{p_user_id:selectedUserId,p_device_id:deviceId});else await rpc("admin_force_logout",{p_user_id:selectedUserId,p_device_id:deviceId});toast(reset?"Reset Device แล้ว ผู้ใช้ยังเปลี่ยนเครื่องได้ตามปกติ":"Force Logout อุปกรณ์แล้ว");await reloadSelectedDevices();if(!demoMode)await loadAll()}catch(x){toast(x.message,true)}finally{buttonBusy(button,false)}});
function openActivity(a=null){const f=$("#activityForm"),items=settings.activities||[],current=a?items.findIndex(x=>x.activity_key===a.activity_key):items.length,total=a?items.length:items.length+1;f.reset();f.elements.position.innerHTML=Array.from({length:total},(_,i)=>'<option value="'+i+'">ลำดับที่ '+(i+1)+(i===0?' (บนสุด)':i===total-1?' (ล่างสุด)':'')+'</option>').join("");f.elements.position.value=String(Math.max(0,current));if(a){["activity_key","name","description"].forEach(k=>f.elements[k].value=a[k]??"");f.elements.enabled.checked=a.enabled;f.elements.visible.checked=a.visible;f.elements.activity_key.readOnly=true}else{f.elements.visible.checked=true;f.elements.activity_key.readOnly=false}$("#activityDialog").showModal()}
$("#addActivityBtn").addEventListener("click",()=>openActivity());$("#activitiesGrid").addEventListener("click",e=>{const b=e.target.closest("[data-edit-activity]");if(b)openActivity(settings.activities.find(x=>x.activity_key===b.dataset.editActivity))});
$("#activityForm").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,button=e.submitter,key=f.elements.activity_key.value,current=(settings.activities||[]).find(x=>x.activity_key===key),activity={activity_key:key,name:f.elements.name.value,description:f.elements.description.value,enabled:f.elements.enabled.checked,visible:f.elements.visible.checked,config:current?.config||{}},ordered=(settings.activities||[]).filter(x=>x.activity_key!==key),position=Math.max(0,Math.min(Number(f.elements.position.value),ordered.length));ordered.splice(position,0,activity);buttonBusy(button,true,"กำลังบันทึก…");try{for(const [index,item] of ordered.entries())await rpc("admin_save_activity",{p_activity_key:item.activity_key,p_name:item.name,p_description:item.description||"",p_enabled:item.enabled,p_visible:item.visible,p_sort_order:(index+1)*10,p_config:item.config||{}});$("#activityDialog").close();toast("บันทึกกิจกรรมและตำแหน่งแล้ว");await loadAll()}catch(x){toast(x.message,true)}finally{buttonBusy(button,false)}});
$("#systemForm").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,button=e.submitter;buttonBusy(button,true,"กำลังบันทึก…");setLoading(true,"กำลังบันทึกการตั้งค่าระบบ…");try{await rpc("admin_save_system_config",{p_system_enabled:f.elements.system_enabled.checked,p_maintenance_mode:f.elements.maintenance_mode.checked,p_maintenance_message:f.elements.maintenance_message.value,p_session_lease_seconds:Number(f.elements.session_lease_seconds.value),p_minimum_version:f.elements.minimum_version.value,p_latest_version:f.elements.latest_version.value,p_update_available:f.elements.update_available.checked,p_update_required:f.elements.update_required.checked,p_update_message:f.elements.update_message.value});toast("บันทึกการตั้งค่าระบบแล้ว");await loadAll()}catch(x){toast(x.message,true)}finally{setLoading(false);buttonBusy(button,false)}});
$("#addReleaseBtn").addEventListener("click",()=>{const f=$("#releaseForm");f.reset();f.elements.enabled.checked=true;f.elements.channel.value="stable";f.elements.status.value="active";$("#releaseDialog").showModal()});$("#releaseForm").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,button=e.submitter;buttonBusy(button,true,"กำลังบันทึก…");try{await rpc("admin_save_release",{p_version:f.elements.version.value,p_enabled:f.elements.enabled.checked,p_required:f.elements.required.checked,p_title:f.elements.title.value,p_release_notes:"",p_download_path:f.elements.download_path.value,p_sha256:f.elements.sha256.value||null,p_size_bytes:null});await rpc("admin_set_release_policy",{p_version:f.elements.version.value,p_channel:f.elements.channel.value,p_status:f.elements.status.value,p_fallback_version:f.elements.fallback_version.value||null});$("#releaseDialog").close();toast("บันทึก Release แล้ว");await loadAll()}catch(x){toast(x.message,true)}finally{buttonBusy(button,false)}});

$("#runtimeForm").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,button=e.submitter,config={browser_timeout_ms:Number(f.elements.browser_timeout_ms.value),request_timeout_ms:Number(f.elements.request_timeout_ms.value),delay_min_seconds:Number(f.elements.delay_min_seconds.value),delay_max_seconds:Number(f.elements.delay_max_seconds.value),max_retry:Number(f.elements.max_retry.value),error_reporting_enabled:f.elements.error_reporting_enabled.checked};buttonBusy(button,true,"กำลังบันทึก…");try{await rpc("admin_save_runtime_config",{p_runtime_config:config,p_retention_days:Number(f.elements.retention_days.value)});toast("บันทึก Remote Config แล้ว");await loadAll()}catch(x){toast(x.message,true)}finally{buttonBusy(button,false)}});
$("#featureFlagsList").addEventListener("change",async e=>{const input=e.target.closest("[data-feature-key]");if(!input)return;input.disabled=true;try{await rpc("admin_save_feature_flag",{p_activity_key:input.dataset.featureActivity,p_feature_key:input.dataset.featureKey,p_name:input.dataset.featureName,p_enabled:input.checked,p_config:{}});toast("อัปเดต Feature Flag แล้ว")}catch(x){input.checked=!input.checked;toast(x.message,true)}finally{input.disabled=false}});
$("#addFeatureBtn").addEventListener("click",()=>{const f=$("#featureForm");f.reset();f.elements.activity_key.innerHTML=(settings.activities||[]).map(x=>'<option value="'+esc(x.activity_key)+'">'+esc(x.name)+'</option>').join("");$("#featureDialog").showModal()});
$("#featureForm").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,button=e.submitter;buttonBusy(button,true,"กำลังบันทึก…");try{await rpc("admin_save_feature_flag",{p_activity_key:f.elements.activity_key.value,p_feature_key:f.elements.feature_key.value,p_name:f.elements.name.value,p_enabled:f.elements.enabled.checked,p_config:{}});$("#featureDialog").close();toast("เพิ่ม Feature Flag แล้ว");await loadAll()}catch(x){toast(x.message,true)}finally{buttonBusy(button,false)}});
function openAnnouncement(a=null){const f=$("#announcementForm");f.reset();f.elements.id.value=a?.id||"";f.elements.title.value=a?.title||"";f.elements.message.value=a?.message||"";f.elements.severity.value=a?.severity||"info";f.elements.enabled.checked=a?.enabled!==false;f.elements.starts_at.value=localDate(a?.starts_at);f.elements.ends_at.value=a?.ends_at?localDate(a.ends_at):"";f.elements.activity_key.innerHTML='<option value="">ทุกกิจกรรม</option>'+(settings.activities||[]).map(x=>'<option value="'+esc(x.activity_key)+'">'+esc(x.name)+'</option>').join("");f.elements.activity_key.value=a?.activity_key||"";f.elements.target_channel.value=a?.target_channel||"";f.elements.target_version.value=a?.target_version||"";f.elements.target_user_id.innerHTML='<option value="">ผู้ใช้ทุกคน</option>'+users.map(x=>'<option value="'+x.id+'">'+esc(x.display_name)+' · @'+esc(x.username)+'</option>').join("");f.elements.target_user_id.value=a?.target_user_id||"";$("#announcementDialog").showModal()}
$("#addAnnouncementBtn").addEventListener("click",()=>openAnnouncement());$("#announcementsList").addEventListener("click",async e=>{const edit=e.target.closest("[data-edit-announcement]"),del=e.target.closest("[data-delete-announcement]");if(edit)openAnnouncement((operations.announcements||[]).find(x=>x.id===edit.dataset.editAnnouncement));if(del&&confirm("ลบประกาศนี้หรือไม่?")){try{await rpc("admin_delete_announcement",{p_id:del.dataset.deleteAnnouncement});toast("ลบประกาศแล้ว");await loadAll()}catch(x){toast(x.message,true)}}});
$("#announcementForm").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,button=e.submitter;buttonBusy(button,true,"กำลังบันทึก…");try{const saved=await rpc("admin_save_announcement",{p_id:f.elements.id.value||null,p_title:f.elements.title.value,p_message:f.elements.message.value,p_severity:f.elements.severity.value,p_activity_key:f.elements.activity_key.value||null,p_enabled:f.elements.enabled.checked,p_starts_at:new Date(f.elements.starts_at.value).toISOString(),p_ends_at:f.elements.ends_at.value?new Date(f.elements.ends_at.value).toISOString():null});await rpc("admin_set_announcement_target",{p_id:saved.id,p_channel:f.elements.target_channel.value||null,p_version:f.elements.target_version.value||null,p_user_id:f.elements.target_user_id.value||null});$("#announcementDialog").close();toast("บันทึกประกาศแล้ว");await loadAll()}catch(x){toast(x.message,true)}finally{buttonBusy(button,false)}});
$("#errorsTable").addEventListener("click",async e=>{const b=e.target.closest("[data-resolve-error]");if(!b)return;const note=prompt("บันทึกการแก้ไข (เว้นว่างได้)")??null;if(note===null)return;try{await rpc("admin_resolve_error",{p_id:Number(b.dataset.resolveError),p_note:note});toast("ปิด Error Report แล้ว");await loadAll()}catch(x){toast(x.message,true)}});
$("#cleanupBtn").addEventListener("click",async e=>{if(!confirm("ลบ Log และ Session ที่เก่ากว่าระยะเวลาที่กำหนดหรือไม่?"))return;buttonBusy(e.currentTarget,true,"กำลังล้าง…");try{const result=await rpc("admin_cleanup_operational_data");toast("ล้างข้อมูลเก่าแล้ว "+Object.values(result).filter(Number.isFinite).reduce((a,b)=>a+b,0)+" รายการ");await loadAll()}catch(x){toast(x.message,true)}finally{buttonBusy(e.currentTarget,false)}});
$("#refreshOperationsBtn").addEventListener("click",async e=>{buttonBusy(e.currentTarget,true,"กำลังตรวจ…");try{await loadAll()}finally{buttonBusy(e.currentTarget,false)}});
$("#feedbackStatusFilter").addEventListener("change",renderFeedback);
$("#refreshFeedbackBtn").addEventListener("click",async e=>{buttonBusy(e.currentTarget,true,"กำลังโหลด…");try{feedback=await rpc("admin_list_feedback",{p_status:null,p_limit:200})||[];renderFeedback()}catch(x){toast(x.message,true)}finally{buttonBusy(e.currentTarget,false)}});
$("#feedbackList").addEventListener("click",async e=>{const button=e.target.closest("[data-save-feedback]");if(!button)return;const card=button.closest("[data-feedback-card]");buttonBusy(button,true,"กำลังบันทึก…");try{await rpc("admin_update_feedback",{p_id:button.dataset.saveFeedback,p_status:$("[data-feedback-status]",card).value,p_admin_note:$("[data-feedback-note]",card).value});toast("บันทึกสถานะข้อเสนอแนะแล้ว");feedback=await rpc("admin_list_feedback",{p_status:null,p_limit:200})||[];renderFeedback()}catch(x){toast(x.message,true)}finally{buttonBusy(button,false)}});
$("#refreshRequestsBtn").addEventListener("click",async e=>{buttonBusy(e.currentTarget,true,"กำลังโหลด…");try{accessRequests=await rpc("admin_list_access_requests",{p_status:null,p_limit:200})||[];renderAccessRequests()}catch(x){toast(x.message,true)}finally{buttonBusy(e.currentTarget,false)}});
$("#accessRequestsList").addEventListener("click",async e=>{const button=e.target.closest("[data-review-request]");if(!button)return;const card=button.closest("article"),note=$("[data-request-note]",card)?.value||"";buttonBusy(button,true,"กำลังบันทึก…");try{await rpc("admin_review_access_request",{p_id:button.dataset.reviewRequest,p_status:button.dataset.status,p_admin_note:note});toast(button.dataset.status==="approved"?"อนุมัติและเปิดสิทธิ์แล้ว":"ปฏิเสธคำขอแล้ว");await loadAll()}catch(x){toast(x.message,true)}finally{buttonBusy(button,false)}});

$("#setupMfaBtn").addEventListener("click",async e=>{if(demoMode){toast("Demo mode");return}buttonBusy(e.currentTarget,true,"กำลังสร้าง…");try{const {data,error}=await supabase.auth.mfa.enroll({factorType:"totp",friendlyName:"VITX Admin"});if(error)throw error;$("#mfaForm").reset();$("#mfaForm").elements.factor_id.value=data.id;$("#mfaQr").innerHTML=data.totp.qr_code;$("#mfaDialog").showModal()}catch(x){toast(x.message,true)}finally{buttonBusy(e.currentTarget,false)}});
$("#mfaForm").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,button=e.submitter;buttonBusy(button,true,"กำลังยืนยัน…");try{const {error}=await supabase.auth.mfa.challengeAndVerify({factorId:f.elements.factor_id.value,code:f.elements.code.value});if(error)throw error;$("#mfaDialog").close();toast("ตั้งค่า MFA สำเร็จ สามารถเปิดบังคับได้แล้ว");await loadAll()}catch(x){toast(x.message,true)}finally{buttonBusy(button,false)}});
$("#toggleMfaBtn").addEventListener("click",async e=>{buttonBusy(e.currentTarget,true,"กำลังบันทึก…");try{await rpc("admin_set_mfa_required",{p_required:!operations.mfa_required});toast(operations.mfa_required?"ปิดการบังคับ MFA แล้ว":"เปิดบังคับ MFA แล้ว");await loadAll()}catch(x){toast(x.message.includes("MFA_VERIFICATION_REQUIRED")?"กรุณาตั้งค่าและยืนยัน MFA ก่อน":x.message,true)}finally{buttonBusy(e.currentTarget,false)}});
$("#mfaChallengeForm").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,button=e.submitter;buttonBusy(button,true,"กำลังยืนยัน…");$(".form-error",f).textContent="";try{const {error}=await supabase.auth.mfa.challengeAndVerify({factorId:f.elements.factor_id.value,code:f.elements.code.value});if(error)throw error;$("#mfaChallengeDialog").close();await enter(pendingMfaSession);pendingMfaSession=null}catch(x){$(".form-error",f).textContent="รหัสไม่ถูกต้องหรือหมดอายุ"}finally{buttonBusy(button,false)}});
boot().catch(x=>{setLoading(false);$("#setupView").classList.remove("hidden");toast(x.message||"เปิดหน้า Admin ไม่สำเร็จ",true)});
